# Generated by Django 3.2.9 on 2021-12-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='product_favourite',
            field=models.ManyToManyField(to='products.Product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='zip_number',
            field=models.CharField(max_length=6),
        ),
    ]
