# Generated by Django 3.2.9 on 2022-01-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options'),
        ('accounts', '0002_auto_20211231_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='product_favourite',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
